### ISSUE TITLE
Newly created ResourceGroups with resources contains no providers or resources

### ISSUE THREAD

**Issue by jonaserikson** [projectkudu/AzureResourceExplorer#177] opened 2017-10-17 08:41 UTC
Subscription with a lot resource groups and resources does not show providers.
Newly created ResourceGroups with resources contains no providers or resources.
The resource groups are listed but empty.

**Comment by davidebbo** [comment] 2017-10-17 15:44
@bala16 I think this is the same root issue as we discussed recently, caused by Explorer not doing paging on the list of resources at subscription level.

**Comment by bala16** [comment] 2017-10-17 17:20
@davidebbo yes. assigning it to myself.

**Comment by bala16** [comment] 2017-10-25 18:03
fixed by 526106d2690bfadee6125a9e5c9b36ac1381d485

**Closed by bala16** 2017-10-25 18:03 UTC
