### ISSUE TITLE
Tenant list returns 500 response

### ISSUE THREAD

**Issue by israels** [projectkudu/AzureResourceExplorer#242] opened 2019-12-12 19:05 UTC
Not sure if there's a better place to post this, but I recently have seen that the tenant drop down in resource explorer is coming up empty (due to https://resources.azure.com/api/tenants returning a 500 response).  I've tried on a couple different accounts, so I'm assuming it's not just a local issue.

I can workaround the issue by pasting a specific subscription id in the URL, but the discovery of tenants and easily swapping doesn't appear to be working currently.

**Comment by balag0** [comment] 2019-12-13 00:26
Yes. This is a recent issue which seems to be impacting west us only. Yesterday we disabled the west us endpoint from traffic manager which fixed the isse for everyone who reported this earlier.
We don't know the root cause yet. 

Can you give it  a try again and post the timestamp here and i can check if the request is somehow getting to west us endpoint or if this is happening in other regions also.

**Comment by israels** [comment] 2019-12-13 00:35
Still occurs for me.  I just tested again a few times (4:33 UTC-8).

**Comment by HiroyukiSakoh** [comment] 2019-12-17 05:44
https://resources.azure.com/api/tenants 500error
ResponseHeader
Date: Tue, 17 Dec 2019 05:41:09 GMT
instance-name: explorer-hk1

**Comment by johnnybegood** [comment] 2019-12-17 08:04
I have the same issue,  500 error on https://resources.azure.com/api/tenants

**Comment by balag0** [comment] 2019-12-17 21:09
Fixed by badfa358ffef7093325f5497624d93fb8d25cd87

**Closed by balag0** 2019-12-17 21:09 UTC
