### ISSUE TITLE
Can not find Change Directory/Tenant option

### ISSUE THREAD

**Issue by IronSean** [projectkudu/AzureResourceExplorer#334] opened 2022-03-31 21:39 UTC
I can not find any options to change AD Directory, and the only relevant issue (#333) is closed with no examples of where to find it.

**Comment by alex-3sr** [comment] 2022-04-04 15:57
Hi,
I confirm that I've the same issue, the dropdown select list is empty ->
![image](https://user-images.githubusercontent.com/38663389/161583757-d595044f-c149-4c7a-9e94-7239879720d4.png)

And if I check F12 console, I can see a 500 on https://resources.azure.com/api/tenants
![image](https://user-images.githubusercontent.com/38663389/161583897-3710cc3a-033d-4f69-a5ce-2748a97f84f4.png)

I'm still not be able to use the tool cross tenants

Thank you
Regards
Alexandre

**Comment by balag0** [comment] 2022-04-04 16:57
Investigating..

**Comment by balag0** [comment] 2022-04-04 18:37
Just checked and seems to be fine now. Could you also check please. @IronSean @alex-3sr 

There was definitely some intermittent issue over the weekend as we had multiple reports so we will continue to investigate and understand the issue.

**Comment by alex-3sr** [comment] 2022-04-04 18:59
Hi,

Thanks for this quick reply. At this time, I still have issue, maybe need wait a bit (if CDN cache, etc..). I tried with inprivate browsing, same issue.

I've to add, that my account has many many several tenants (maybe more than 30 or 40, never count them). And already have issue on Azure Devops for example, when service connection wizard tried to list all subcriptions in all tenants, and finish in timeout. So, don't know if it can help you but I think it could be interesting to precise that I have several tenants on my accounts.

Thanks,
Alex

**Comment by alex-3sr** [comment] 2022-04-04 19:18
For complet my previous comment, I just did a `(Get-AzTenant).count` and got 51. I know that there are a 50 limit subscription display, maybe a same limitation on tenant too ?

**Comment by lukeb2e** [comment] 2022-04-05 12:21
I do have the same issue - But I am only member of 2 tenants. 
![image](https://user-images.githubusercontent.com/12938238/161751979-e2a45867-a49a-4248-bca0-1b676db8dcc5.png)

Seems that the backend has been turned off - this is the message I receive when I try to access `https://resources.azure.com/api/tenants` directly.
![image](https://user-images.githubusercontent.com/12938238/161752275-18c1ab74-2b8c-4c56-bf71-3297fd93558c.png)

**Comment by balag0** [comment] 2022-04-05 23:33
Yes, I can also repro this now. Will post an update soon. Thanks.

**Comment by balag0** [comment] 2022-04-06 20:51
Update - We understand the issue and also why it was failing transiently. Fix deployment might take a few more days though.

**Comment by vidarkongsli** [comment] 2022-09-09 06:12
> Update - We understand the issue and also why it was failing transiently. Fix deployment might take a few more days though.

I'm still experiencing this problem.

**Comment by alex-3sr** [comment] 2022-09-09 07:31
Hi everyone, I can confirm that issue still exist here too :(
I'm able to workaround it, by using LightHouse, but I don't have all remote tenants associated with LightHouse, So i really need it working as expected

**Comment by balag0** [comment] 2022-12-13 23:58
Sorry. missed updating and resolving this thread. the fix was deployed by April 8 and verified using the local repro that was failing earlier.
If this is still failing it must be a different issue. Please open a separate issue to avoid confusion.

**Closed by balag0** 2022-12-13 23:58 UTC
