### ISSUE TITLE
OperationalInsights data sources error

### ISSUE THREAD

**Issue by jonsabo** [projectkudu/AzureResourceExplorer#127] opened 2016-12-13 20:07 UTC
Trying to browse to an OMS workspace > dataSources seems to always throw this error

```
{
  "data": {
    "error": {
      "code": "KindNotSpecified",
      "message": "Must specify a valid kind filter. For example, $filter=kind eq 'windowsPerformanceCounter'."
    }
  },
  "status": 400
}
```
and then does not show any dataSources.

It was happening on a workspace I've been using for a while, and also just tested it on a brand new one. Going by the error, I am guessing it is because the API does not allow you to just list all datasources, you can only get them for a specific `kind` at a time. I believe the available `kind`s are:

AzureActivityLog
AzureAuditLog
CustomLog
LinuxPerformanceObject
LinuxSyslog
WindowsEvent
WindowsPerformanceCounter

**Comment by davidebbo** [comment] 2017-02-09 18:16
Can you check what specific ARM request is being made? Is it an API issue or an Explorer issue?

**Comment by rwwilden** [comment] 2018-02-01 12:28
This error still occurs. How can I check what ARM request is being made?

**Comment by davidebbo** [comment] 2018-02-01 18:01
The URL is shown next to the GET/POST button in the UI.

Closing since the issue is almost certainly specific to the resource provider, and not in Resource Explorer.

**Closed by davidebbo** 2018-02-01 18:01 UTC

**Comment by rwwilden** [comment] 2018-02-02 06:31
In this case there is no url next to the GET/POST button, really strange...
Added a screenshot of what happens.

![image](https://user-images.githubusercontent.com/617960/35719728-0c8e487c-07eb-11e8-9c6f-c592488e9130.png)

**Comment by bala16** [comment] 2018-02-02 08:04
This is a limitation with Resource Explorer. The only query string parameter supported is api version. since filter needs to be passed as a querystring parameter, ARM APIs that have required kind parameter won't work on Explorer. there is no way to provide values for the filter in resource explorer.

You can use explorer raw mode ( https://resources.azure.com/raw/ ) to make such requests.
The format for the arm request will look something like

GET https://management.azure.com/sub/subid/resourcegroups/rg/providers/microsoft.insights/items?$filter=(kind eq 'windowsperformancecounter')&api-version=2016-01-01

Select the entire line and press Control+S to make the ARM call.
