### ISSUE TITLE
Access to resources.azure.com was denied

### ISSUE THREAD

**Issue by manuelcprosa** [projectkudu/AzureResourceExplorer#350] opened 2022-09-29 13:19 UTC
Hi team,

It seems that the access to Resources.azure.com is showing the following error: "Access to resources.azure.com was denied".

Was the service discontinued? 
Thanks!

**Comment by ryanborMSFT** [comment] 2022-09-29 15:24
Hey there @manuelcprosa, thanks for the heads up. We are seeing this internally as well. I'm reaching out to the owning team now to get this sorted - Stay tuned.

**Comment by el-pato** [comment] 2022-09-29 17:19
Experiencing same thing here. Didn't get any email alerts, https://status.azure.com is all green, and no relevant entries in the service health dashboard in Azure.

Some more information, in case it's relevant: I am trying to upgrade a Function's runtime to .net6, which can be done via the Azure Resource Explorer or the Azure CLI. Since the resource explorer appears to be down, I tried the relevant Azure CLI command 

```az functionapp config set --net-framework-version v6.0 -n <function-app-name> -g <resource-group-name>```

The command _seems_ to run successfully, but I still get the "unsupported runtime" warning in the Azure portal. Perhaps the issue is deeper than just the Azure Resource Explorer?

**Comment by balag0** [comment] 2022-09-29 21:08
Sorry for the delay in updating the status. Yes this a regression and we are actively working on resolving the 403 error.
Will post an update once the issue is mitigated.

@el-pato I think that error is unrelated to this issue. Could you open an issue at 
https://github.com/Azure/Azure-Functions/issues

**Comment by balag0** [comment] 2022-09-29 22:06
This should be working now.

**Comment by David-W-Williams** [comment] 2022-09-29 22:51
@balag0 It started working for me.  Thanks for the update.

**Comment by kesselringt** [comment] 2022-12-07 17:48
Hello, I see this issue is a couple months old, but it seems to have resurfaced. Nothing seems to be down on the Azure side as far as I can tell.

**Comment by kesselringt** [comment] 2022-12-14 14:12
Huh... Well that works now. I swear I tried that last week via a private browser but still didn't work, but now it does. Well at least I have a way in thanks!

> Are you using a user from the tenant or a guest account? I got the same problem and for one tenant it worked, but when I switched if gave the 403. But using a user created in that tenant, everything worked. Perhaps this is not the expected behaviour, but it could be used as a temporary fix.

**Comment by wirelessy** [comment] 2023-02-09 11:31
It is happening to me and my team aswell. Support is forwarding me here.
Requesting help aswell.

**Comment by aaron-champion** [comment] 2023-02-09 18:21
I have a user experiencing this issue past few days, even in a private browser session. Other users including myself have no problems accessing and I can't figure out why just the one user. If it is a permissions or account setting that the user is missing, I can't think of what it could be.

**Comment by balag0** [comment] 2023-02-22 21:19
Fix was deployed Sept 29. This should have resolved (and we also have confirmation on this thread) the regression mentioned above.So resolving this issue to avoid confusion.

Regarding subsequent failures, could you please open separate issues with any interesting details in the setup. Sorry for the extra work but this would help us identify the scenarios better. Thanks

**Closed by balag0** 2023-02-22 21:19 UTC
